### ISSUE TITLE
Actors Picture And Data is displayed Wrong[BUG]

### ISSUE THREAD

**Issue by Evendur** [MaterialFoundry/MaterialDeck#101]
**Setup**
 - OS: Windows 10
 - Browser: Foundry App
 - Module version: 1.4.12
 - Foundry version: 10 Build 288
 - Gaming system & version: Pathfinder 1 0.82.2
 - Any other modules enabled: yes

**Describe the bug**
When i want to display Combatants in the Combat Tracker i get only shown the same Picture on my Stream Deck for place 2-9, Place 1 is empty and only the Black Background is visible. The Function works it selects the Token which is in the Initiative Order, only the Picture, Name and HP is from on and the same token.

If i advance in the Initiative Order it Changes sometimes the Picture.

If i use one of the Prebuild Profiles it works as it should, with the same settings i use in my Build.

**Screenshots**
<img width="401" alt="Screenshot 2022-11-06 141446" src="https://user-images.githubusercontent.com/20979440/200172802-4c9d03da-15a3-4159-aac0-622d0058e55d.png">
<img width="416" alt="Screenshot 2022-11-06 141419" src="https://user-images.githubusercontent.com/20979440/200172807-6736de78-84dd-4564-bb2f-d7af2c307183.png">

These Two Pictures Show my Settings 

<img width="1360" alt="Screenshot 2022-11-06 141333" src="https://user-images.githubusercontent.com/20979440/200172817-94d4f246-9a2a-4bcf-abb2-6a45b696e010.png">
<img width="1328" alt="Screenshot 2022-11-06 141359" src="https://user-images.githubusercontent.com/20979440/200172813-ac14a842-e871-415e-a456-6e69b0187af2.png">

<img width="401" alt="Screenshot 2022-11-06 142735" src="https://user-images.githubusercontent.com/20979440/200173452-710348cb-272b-476b-bc1d-35dc774854c4.png">
And this is how it looks with one of the Provided Profiles

**Console Log**

streamdeck connected to server 1.1.0
8commons.js:1703 Error: You are accessing the Combatant#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Combatant._logV10CompatibilityWarning (commons.js:6617:14)
    at get data [as data] (commons.js:6517:24)
    at CombatTracker.update (combattracker.js:45:47)
    at analyzeWSmessage (MaterialDeck.js:169:27)
logCompatibilityWarning @ commons.js:1703
_logV10CompatibilityWarning @ commons.js:6617
get data @ commons.js:6517
update @ combattracker.js:45
analyzeWSmessage @ MaterialDeck.js:169
await in analyzeWSmessage (async)
ws.onmessage @ MaterialDeck.js:232

**Additional context**

**Comment by CDeenen** [comment]
I have just released v1.5.0 which is compatible with Foundry v11. I cannot replicate this issue now, so I assume it is fixed. Otherwise, please let me know.

**Comment by CDeenen** [comment]
This has been fixed in the latest version.
