### ISSUE TITLE
Latest version of "About time" has depreciated Gametime.DTNow()

### ISSUE THREAD

**Issue by daft-develop** [MaterialFoundry/MaterialDeck#102]
Currently using material deck 1.4.12 and about time 10.0.1, which has dropped support for Gametime and instead defers to the system game.time

Line below reports an error for missing function every time it tries to refresh game time on the deck

https://github.com/CDeenen/MaterialDeck/blob/631fdbcccb559c060c297ac8fbb0690e33c15bc1/src/actions/external.js#L481

I used the following on my local copy to fix the error, replacing the line above. It's based on the old longDateExtended() function from "about time" using the latest SimpleCalendar api.

```js
let dateObj = SimpleCalendar.api.timestampToDate(game.time.worldTime);
let currentTime = {
          year: dateObj.year,
          years: dateObj.year,
          month: dateObj.month + 1,
          months: dateObj.month + 1,
          day: dateObj.day + 1,
          days: dateObj.day + 1,
          hour: dateObj.hour,
          hours: dateObj.hour,
          minute: dateObj.minute,
          minutes: dateObj.minute,
          second: dateObj.second,
          seconds: dateObj.second,
          dow: dateObj.dayOfTheWeek,
          dowString: dateObj.display.weekday,
          monthString: dateObj.display.monthName,
          yearName: dateObj.display.yearName
}
```

**Comment by CDeenen** [comment]
In v1.5.0 About Time compatibility has been replaced with Simple Calendar, so it should now work properly.

**Comment by daft-develop** [comment]
Tested v1.5.0 in Foundry V11 and confirmed working as expected. Thanks!
