### ISSUE TITLE
[BUG] Playlist doesn't seem to work on newer version of foundry.

### ISSUE THREAD

**Issue by christianhurley** [MaterialFoundry/MaterialDeck#103]
**Setup**
 - OS: Windows
 - Browser: Chrome
 - Module version: 1.4.12
 - Foundry version: [e.g. 10]
 - Gaming system & version: PF2e
 - Any other modules enabled: Yes

**Describe the bug**
When trying to add playlists to the stream deck, nothing is seen. The profile doesnt work either

**Screenshots**
![image](https://user-images.githubusercontent.com/33719181/228300161-6c017378-ca92-4d50-ad1d-0b88034b4cdd.png)

**Additional context**
I am aware that i am using a higher version of foundry than what is supported. So if you dont want to be notified about bugs in later version, please close the issue.

**Comment by CDeenen** [comment]
I have just updated the module to v1.5.0 which is compatible with v11. I cannot replicate this issue, so I assume it has been fixed. If not, please let me know.
