### ISSUE TITLE
NotYourTurn! External Module Issue

### ISSUE THREAD

**Issue by t3chn0manc3r** [MaterialFoundry/MaterialDeck#104]
**Setup**
 - OS: Windows
 - Browser: Foundry app
 - Module version: 1.5.1
 - Foundry version: 11.305
 - Gaming system & version: pf2e 5.1.1
 - Any other modules enabled: Yes

**Describe the bug**
NotYourTurn is not responding to any of the buttons on the Stream Deck.

**Screenshots**
N/A - Nothing happens

**Console Log**
Nothing appears in log.

**Additional context**
After doing some digging, looks like Material Deck was attempting to call the Hook "setNotYourTurn" in external.js -> keyPressNotYourTurn function, but I was looking through the NotYourTurn module and it looks like that doesn't exist in the version I was using (2.1.1). The hook just appears to be called "NotYourTurn" now. I edited the hook call on the Material Deck side manually and that appears to have done the trick, so figured I'd give you a heads up there.

**Comment by MaterialFoundry** [comment]
This should be fixed in the latest version
