### ISSUE TITLE
[BUG] "SD Application Not Connected" after upgrading from 1.5 to 1.6 and from MaterialServer to MaterialCompanion

### ISSUE THREAD

**Issue by coffiarts** [MaterialFoundry/MaterialDeck#113]
Am I the only one having this?

**Setup**
 - OS: Win 10
 - Browser: Froudry App (Electron Client)
 - Module version: 1.6.2, in combination with MaterialCompanion 25.9.2 (latest)
 - Foundry version: 11.308
 - Gaming system & version: tde5 - version 5.1.5
 - Any other modules enabled: tons of them ;-) (but haven't changed any of them when upgrading to MaterialDeck 1.6.2)

**Describe the bug**
After upgrading MD from 1.5.1 to 1.6.2, and switching from Material Server to Material Companion, as recommended, connection to my Streamdeck doesn't initialize anymore.

**Screenshots**
**Before** (with MD 1.5.1 and Material Server), everything worked fine:
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/39616483/13bc13d4-2d09-47a1-837a-9bbd2361e825)

**After** (with MD 1.6.2 and Material Companion), I can't get Streamdeck to connect (whereas connection to Foundry is still fine):
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/39616483/a78b484a-4a8a-458c-ae26-b3e908505628)
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/39616483/057cfdcb-782e-4656-903e-d8f7ec9936a5)

Both screenshots were taken with the game running for at least 2-3 minutes (in order to give enough time for proper initialization)

**Console Log**
Yes there _are_ errors related to MD and its dnd5 script that comes packaged with it, but it is important to know that this error has already been there **before** upgrading. So I don't see why this should be the cause (apart from the fact that I am not playing dnd5 anyway):
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/39616483/4f051a76-cf42-478a-ac5a-affcbccf22ae)

**Additional context**
Nothing to add that I'd be aware of

**Comment by CDeenen** [comment]
I assume the Material Companion version you're reporting is a typo, because the latest version is v1.0.2

First of all, we don't need to look at the Foundry side, since that seems to be connecting fine. The console errors you're reporting is probably because your system is not supported by Material Deck, meaning the module will treat it as if it's dnd5e. If this hasn't been an issue before it shouldn't be an issue now.

The first thing you'll want to check is if you've also updated the Stream Deck plugin. The previous version is, just like the module, incompatible with Material Companion. 
Also, please make sure you're not running Material Server. And restarting everything (including your computer) is always worth a try.

**Comment by coffiarts** [comment]
You're absolutely right - I simply missed to realize that the SD plugin itself needs to be updated as well.
I'll close the issue at once. Consider this as a Non-RTFM case ;-)
Concerning the Material Companion version: I picked it from the version file inside the installation dir. But it's probably just some technical build number.
So thanks for the clarification, and sorry for my dumbness.

**Comment by coffiarts** [comment]
You're absolutely right - I simply missed to realize that the SC plugin itselfs needs to be updated as well.
I'll close the issue at once. Consider this as a Non-RTFM case ;-)
Concerning the Material Companion version: I picked it from the version file inside the installation dir. But it's probably just some technical build number.
So thanks for the clarification, and sorry for my dumbness.

**Comment by coffiarts** [comment]
You're absolutely right - I simply missed to realize that the SC plugin itselfs nedds to be updated as well.
I'll close the issue at once. Consider this as a Non-RTFM case ;-)
Concerning the Material Companion version: I picked it from the version file inside the installation dir. But it's probably just some technical build number.
So thanks for the clarification, and sorry for my dumbness.
