### ISSUE TITLE
Player Avatar

### ISSUE THREAD

**Issue by MrTranscended** [MaterialFoundry/MaterialDeck#39]
Add an option to swap out players avatar via SD.

**Comment by CDeenen** [comment]
Thanks for your suggestion.

Are you aware of a module that can do that? I'd be happy to look for a way to trigger such a module using Material Deck.
The main goal of Material Deck is to make it easier to trigger functions that already exist in Foundry (or enabled by other modules), not so much to add completely new things, unless those things only make sense in combination with a SD.
Such features could be useful to anyone, so it doesn't make much sense to force people to use a SD for it.

You could also look into using a macro to do that, and then triggering the macro using Material Deck.

**Comment by CDeenen** [comment]
Closing this since there has been no reply
