### ISSUE TITLE
Unable to use on externally hosted instances

### ISSUE THREAD

**Issue by Puddinglord** [MaterialFoundry/MaterialDeck#59]
I use `The Forge` as my hosting service for FoundryVTT. I tried using Material Deck on my instance but I have since realized that there is an error regarding the module trying to make an unsecured connection from an HTTPS connection.

Could you update the client and server to connect over Secure Web Sockets (WSS)? This would allow people using third party hosting solutions that use HTTPS standard to use Material Deck as I really want to use it for my games.

Thanks!

**Comment by CDeenen** [comment]
Hey, it should work fine with the Forge. I expect that you filled in the wrong IP address in the module settings. This should be the IP of Material Server, not your Foundry server, see https://github.com/CDeenen/MaterialDeck/wiki/Installation#installing-the-server and https://github.com/CDeenen/MaterialDeck/wiki/Module-Setup.

Could you please check that?

**Comment by Puddinglord** [comment]
The IP that I put in the module settings is the external IP address of the machine running the Material Server. I have it port forwarded as well.

Here are the errors in the console explaining what I said above. 
![Screen Shot 2020-12-27 at 6 30 10 AM](https://user-images.githubusercontent.com/4474799/103169801-1213e300-480d-11eb-8b2c-f9d9c3f4708a.png)

You can also see the IP and port I'm trying to connect to in that image. Let me know if you need anything else from me.

**Comment by CDeenen** [comment]
Right now you're supposed to run Material Server on your local computer. I chose to not use secure websockets to save people the hassle of having to work with SSL certificates.
Using a remote server also slows the connection down unnecessarily, because it will send the data from your browser to the remote server, and then back to your computer to the Stream Deck application.

**Comment by Puddinglord** [comment]
I am running the material server on my local machine. That external IP is that machine I'm writing this response from. The Forge runs, as far as I know, AWS. I don't have access to the server that my Foundry instance is running from. They don't allow it.

![Screen Shot 2020-12-27 at 7 01 38 AM](https://user-images.githubusercontent.com/4474799/103170339-78026980-4811-11eb-9b1c-1359cf99a06f.png)

I understand what your intent is, and I know that I can get this working if I run Foundry locally and the Material server local to it as well. I am not in this position, and my Foundry instance is remote, and I have no way of making the Material server local to it. I'm not saying make the secure route the default, I'm asking if it could be supported for people like me who use third-party hosting services for their Foundry instances.

**Comment by CDeenen** [comment]
Material Server and the Stream Deck application never talk directly to the Foundry server, instead they talk to your browser. It should not be relevant if the Foundry server is hosted locally or remote.

Looking at the screenshot of the console, you've set the IP address up so it tries to access a public IP address. Both your browser and Material Server are running locally, so could you try setting it to localhost:3001?

**Comment by Puddinglord** [comment]
Alright, I see the workflow now. I misunderstood how this was working. I set the local IP (to my router not external).

The issue still stands though. I get that it should be communicating locally which it could but since the page is HTTPS the browser will **not** allow an unsecured WebSocket to spawn. That would go against having a secured page and by the WebSocket standard, this is not allowed. If the page is HTTPS then the WebSocket must be at the same or greater security level.

![Screen Shot 2020-12-27 at 7 32 39 AM](https://user-images.githubusercontent.com/4474799/103170870-c1ed4e80-4815-11eb-82dd-6daa36cefe75.png)

**Comment by CDeenen** [comment]
As far as I know it will actually allow an unsecured websocket, as long as the websocket server is local. I have tested this with the Forge, and it worked fine for me, and I think there are other people using it with the Forge.

**Comment by Puddinglord** [comment]
I messaged you on Discord as I feel like this could be solved faster there. What browser did you use to test this with The Forge?
