### ISSUE TITLE
Ability to have a scene control menu like macros

### ISSUE THREAD

**Issue by Puddinglord** [MaterialFoundry/MaterialDeck#63]
I would love it if I could make a menu on the stream deck that listed all the scenes I have or the ones that I want to know about. That way I could change scenes from the stream deck. I know I can do this if the scenes are loaded into the "navigation" view but I have 30+ scenes and that takes up a lot of room at the top of the screen.

**Comment by CDeenen** [comment]
Definitely something I'd like to see as well. Added to the list of planned features

**Comment by CDeenen** [comment]
Should've closed this earlier, since this already got added a month ago :p
