### ISSUE TITLE
Possible integration with Token HUD?

### ISSUE THREAD

**Issue by Puddinglord** [MaterialFoundry/MaterialDeck#64]
Token HUD automatically parses that token's character sheet and grabs the attacks and skills and such. It would be awesome if the token control function could do the same thing. I know I can set up macros for attacks but that's a lot of macros for a full-sized campaign. If you could populate the stream deck with all the parsed attacks and skills that would be epic.

**Comment by CDeenen** [comment]
Not the easiest thing to add, but I've added it to the list of planned features

**Comment by CDeenen** [comment]
This has been added in the last update
