### ISSUE TITLE
Bug: Token Control Speed Values Not Showing Up

### ISSUE THREAD

**Issue by Puddinglord** [MaterialFoundry/MaterialDeck#65]
![Screen Shot 2020-12-27 at 5 21 02 PM](https://user-images.githubusercontent.com/4474799/103180868-e7a34380-4867-11eb-9004-64e4d319b166.png)

AC right next to it works just fine. Nothing is showing value-wise for a token's speed though.

**Comment by CDeenen** [comment]
I'm aware, I closed that issue a few minutes ago since I already fixed it: https://github.com/CDeenen/MaterialDeck/issues/55. 
Will be in the next update :)
