### ISSUE TITLE
Problem with saving settings in elgato streamdeck softwere

### ISSUE THREAD

**Issue by cirkusapan** [MaterialFoundry/MaterialDeck#71]
Filled fields on material deck plugin in streamdeck does not save for me if jumped to another action, if I select another field in the same action before moving to the next the filled fields get saved. This seems like a bug but don't know if its fixable.

**Comment by CDeenen** [comment]
I am aware of this issue, but I haven't looked properly at fixing it yet. I expect it is fixable, I will give it a try.

**Comment by CDeenen** [comment]
This has been fixed in v1.4.6 (you'll need to update the Stream Deck plugin: https://github.com/CDeenen/MaterialDeck_SD/releases/tag/v1.4.6)
