### ISSUE TITLE
[FEATURE/Issue] "Stop All Playlist" just pauses, not stops.

### ISSUE THREAD

**Issue by Musrha** [MaterialFoundry/MaterialDeck#82]
**Is your feature request related to a problem? Please describe.**
When you use the option Stop All Playlists, all the sounds just get paused (and they don't fade out) and not fully stopped.

**Describe the solution you'd like**
The option to choose in the Stream Deck the usual behaviour vs a full stop of the sounds.

(Thanks in advance!)

**Comment by CDeenen** [comment]
This has been added to v1.4.6
