### ISSUE TITLE
[BUG] - Freezes Stream Deck Software

### ISSUE THREAD

**Issue by Kellender13** [MaterialFoundry/MaterialDeck#86]
**Setup**
 - OS: Windows
 - Browser: Chrome
 - Module version: 1.4.6
 - Foundry version: 0.8.9
 - Gaming system & version: dnd5e 1.5.3
 - Any other modules enabled: yes

**Describe the bug**
Even with Foundry Not Open I am unable to Click on any of the icons in the Stream Deck Software without it freezing and having to restart the software.  This only happens on the material deck Functions

**Comment by CDeenen** [comment]
First of all, could you please make sure that you use the latest version of the Stream Deck software and Material Deck plugin.

Does it matter if you have Material Server running or not?

If you enable debugging, we could take a look to see if any errors appear. You can enable it by following the guide here: https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/
(Scroll down to the debugging heading).
After enabling that, head over to http://localhost:23654/ in Chrome, and you should see multiple pages: 
![image](https://user-images.githubusercontent.com/68693756/140553066-7c317bd7-c951-4a1c-8dea-43b88739fb17.png)

The one named 'com.cdeenen.materialdeck [function name] Inspector' (top one in the above image) should only appear after clicking on an icon. And you might have other pages if you have other plugins enabled.

From this page, could you click on each one, click an icon in the SD software, and look for any errors.

**Comment by CDeenen** [comment]
Closing this since there's been no response
