### ISSUE TITLE
Weather controls dont work on press

### ISSUE THREAD

**Issue by Mechrior** [MaterialFoundry/MaterialDeck#87]
when using the FX Master button, if i press something like "snow" or "rain", nothing happens on the first press, and on the second press it only plays the animation over the scene for maybe 2 seconds then dissappears.

**Comment by CDeenen** [comment]
Hey, there has been some problems with the FX Master integration for a while now, due to an update to FX Master. This is planned to be fixed in the next update.

**Comment by Mechrior** [comment]
ah ok, thanks for the quick response.

Your module was one of the main reasons I pulled the trigger on buying foundry.

I love hardware integration in my gaming.
