### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mechrior** [MaterialFoundry/MaterialDeck#88]
**Setup**
 - OS: Windows 10
 - Browser:Stream Deck XL
 - Module version: 1.4.6
 - Foundry version: 0.8.9
 - Gaming system & version: D&D5e 1.5.3
 - Any other modules enabled: yes

**Describe the bug**
when trying to use the token wildcard feature, only the current token picture is displayed on the top row 3rd button.
All the other icons are black but pressing them does switch to a diferent icon.

**Screenshots**
Problem is on streamdeck itself not on VTT

**Console Log**
foundry.js:19457 You are calling PlaceableObject#update which has been deprecated in favor of Document#update or Scene#updateEmbeddedDocuments. Support will be removed in 0.9.0
<html>
<body>
<div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(32, 33, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div tabindex="-1" class="console-message-wrapper console-from-api console-warning-level console-selected" role="treeitem" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: rgb(65, 115, 180); border-bottom: 1px solid rgb(65, 115, 180); background-color: rgb(41, 50, 61);"><div class="console-message repeated-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 4px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

update | @ | foundry.js:19457
-- | -- | --
  | keyPress | @ | token.js:613
  | async function (async) |   |  
  | keyPress | @ | token.js:586
  | analyzeWSmessage | @ | MaterialDeck.js:157
  | ws.onmessage | @ | MaterialDeck.js:196

</span></div></div></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by CDeenen** [comment]
Hey, it looks like this is because the default profile wasn't updated when I made a change to how button icons are determined.
To fix this, click the button in the SD application, scroll down until you get the 'icon' option near the bottom, set it to 'Default'.
Unfortunately, you'll have to do this for each button.
