### ISSUE TITLE
Macro board icons and names not changing

### ISSUE THREAD

**Issue by Mechrior** [MaterialFoundry/MaterialDeck#89]
**Setup**
 - OS: Windows
 - Browser: None, streamdeck issue
 - Module version: 1.4.6
 - Foundry version: 0.8.9
 - Gaming system & version: D&D5e 1.5.3
 - Any other modules enabled: yes

**Describe the bug**
I have been looking intothe macroboard feature, but I am coming across a bug where the macro on the stream deck just has the dice surrounded by a target ring, and "new macro" as text across the middle. It is not showing the icon change or the name of the macro on the actual stream deck itself.

**Console Log**
Dont know if this is the pertinent information you would need in respect to this issue but there is a call:
DevTools failed to load SourceMap: Could not load content for http://localhost:30000/modules/Equipment-Paper-Doll/scripts/lib/popperJs/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:30000/modules/dungeon-draw/scripts/lib/pixi-filters.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:30000/modules/dungeon-draw/scripts/lib/jsts.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:30000/modules/merchantsheetnpc/bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Thanks for any help again! loving the module! Would not play without it now!

**Comment by CDeenen** [comment]
Hey, I can't replicate your issue.

Could you double check that the action settings are correct in the Stream Deck software. You'll want to make sure that 'Mode' is set to 'Macroboard', and that the 'Macro Number' corresponds with the number in the 'Macro Configuration':
![image](https://user-images.githubusercontent.com/68693756/142442277-33b43eca-da14-4d0e-b693-a4705a8c3469.png)
![image](https://user-images.githubusercontent.com/68693756/142442717-45d78e30-497e-4784-bbf5-6dd260bc67f3.png)

I don't think those errors are from Material Deck, they look to be from 'equipment paper doll', 'dungeon draw' and 'merchant sheet npc'.
Could you monitor the console while changing either the macro name, macro image, or the settings in the Stream Deck software?

**Comment by Mechrior** [comment]
will o this in the morning vefore my players turn up and get back to you.

**Comment by Mechrior** [comment]
Strangely enough, running the software this morning so that my audio controls work in a certain app, the controls for those macro's are now showing properly. no errors or issues in the debug log
