### ISSUE TITLE
[FEATURE] Add offset option to 'Other Actions' -> 'Control Buttons'

### ISSUE THREAD

**Issue by Mechrior** [MaterialFoundry/MaterialDeck#90]
**Is your feature request related to a problem? no

**Describe the solution you'd like**
Would it be possible to add an ofset option to the visible tools on the "control buttons" menu? I have several modules that increase the amount of buttons on each bar beyond the 16 available under the standard layout.

**Describe alternatives you've considered**
creating a seperate page/folder for those icons specifically. But this would mean going into another folder rather than just pushing one button to change the currently displayed icons. Lazy I know but something I love on the token control wildcards button.

**Comment by CDeenen** [comment]
That should be possible. I'll try to add it in the next update.

**Comment by CDeenen** [comment]
This has been added to my local build, and will be in the next update
