### ISSUE TITLE
[Request] Option to turn token movement orientation

### ISSUE THREAD

**Issue by LonePaladin** [MaterialFoundry/MaterialDeck#92]
I use a shared TV to display maps with my live group; the TV sits in the middle of the table, with everyone sitting around it. This means that, for some players, their view is oriented differently -- for them, "north" is the bottom of the screen and all the text is upside-down. (This actually helps my dyslexic player; she can read upside-down text more readily than normal).

If I used a Stream Deck to pass around the table, for the players to control their own tokens, they would have to keep the device oriented in the same direction as the TV. This means they'd be looking at their macro icons either on their side, or upside down.

I'd like to see an option to change the orientation of the movement keys -- perhaps a key that simply turns that entire section 90 degrees. Make the key for moving north a different color, so that the user can easily tell which way it's expecting to go.

**Comment by CDeenen** [comment]
Sorry for not getting back at you earlier. 
I have been thinking about this, and I think that the easiest solution is to use the features that are already available:
Create 4 pages or profiles, each identical, except for the movement direction. You can manually change the icons so the arrows point in the right direction (see: https://github.com/CDeenen/MaterialDeck/wiki/Custom-Icons), and add a colored background to the northern facing arrow. You can then add some buttons which change to a different page or a different profile.
