### ISSUE TITLE
[BUG] "Stop All Playlists" only shows first playlist, not current one.

### ISSUE THREAD

**Issue by tehguitarist** [MaterialFoundry/MaterialDeck#93]
**Setup**
 - OS: MacOS
 - Browser: Firefox
 - Module version: 1.4.8
 - Foundry version: 9.242
 - Gaming system & version: dnd5e
 - Any other modules enabled: yes, though none playlist related 
 
On the stream deck, I have selected "Display Current Playlists", but whilst it is showing a correct indication of whether a playlist is playing or not, and stopping correctly, it is only showing the first playlist (which is currently a soundboard playlist, though changing it to sequential doesn't seem to have an effect. The same behaviour happens on Pause All. When changing playlists it stays the same name.

**Comment by CDeenen** [comment]
Sorry for the late response.

The 'Display Current Playlist' option is not meant to display the currently playing playlist, instead it is meant to display the playlist at the current offset.

Example usecase:
If you want to display 1 playlist on the SD, and want to use 'relative offset' to scroll through your playlists, you can display the current playlist on the pause or stop button, and the target playlist on the offset buttons. 
See the image, the top-right button increases the playlist offset by 1, which opens the next playlist named 'Darkraven Fantasy ...'. The button left of that pauses all tracks and displays the current playlist ('Michale Ghelfi Music'). The top-left button decreases the playlist offset by 1, which opens the previous playlist named 'Michael Ghelfi Ambience'.
![image](https://user-images.githubusercontent.com/68693756/163659012-12167e29-866e-4b5f-86d1-14ec616e2736.png)
