### ISSUE TITLE
[BUG] Roll Dice returns NaN in the chatbox

### ISSUE THREAD

**Issue by Kirsham** [MaterialFoundry/MaterialDeck#94]
When using the Roll Dice functionality on the Stream Deck, the chat output reads NaN. The actual roll(s) do(es) go through and can be viewed by expanding the chat message. All individual dice rolls and their sum can be viewed through this workaround, but any bonuses are not included. The example below is on a fresh world: v9 build 255, D&D 5e 1.5.7, and no modules enabled except MaterialDeck v1.4.8.

![image](https://user-images.githubusercontent.com/72575642/160298407-df97b3bf-1767-4786-867a-076cf05a63e2.png)

**Comment by CDeenen** [comment]
I can reproduce this. I'll look into fixing it in the next update.
Thanks for the bug report.

**Comment by CDeenen** [comment]
This should be fixed in the latest update (v1.4.9)
