### ISSUE TITLE
[BUG] Foundry v10 

### ISSUE THREAD

**Issue by shecrio** [MaterialFoundry/MaterialDeck#98]
**Setup**
 - OS: windows
 - Browser: Foundry app
 - Module version: 1.4.10
 - Foundry version: 10.284
 - Gaming system & version: dnd5e 2.0.2
 - Any other modules enabled: no

**Describe the bug**
Each icon that tries to load an image from foundry or button press that tries to interact with foundry throws an error.

**Console Log**
commons.js:4618 Uncaught (in promise) Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (commons.js:3630)
    at SchemaField.validate (commons.js:3357)
    at Setting.validate (commons.js:4994)
    at new DataModel (commons.js:4771)
    at new Document (commons.js:5310)
    at new BaseSetting (commons.js:9319)
    at new ClientDocumentMixin (foundry.js:12942)
    at new Setting (foundry.js:21144)
    at ClientSettings.get (foundry.js:2718)
    at analyzeWSmessage (MaterialDeck.js:137)
ModelValidationError @ commons.js:4618
_validateType @ commons.js:3630
validate @ commons.js:3357
validate @ commons.js:4994
DataModel @ commons.js:4771
Document @ commons.js:5310
BaseSetting @ commons.js:9319
ClientDocumentMixin @ foundry.js:12942
Setting @ foundry.js:21144
get @ foundry.js:2718
analyzeWSmessage @ MaterialDeck.js:137
async function (async)
analyzeWSmessage @ MaterialDeck.js:135
ws.onmessage @ MaterialDeck.js:209

**Additional context**
Foundry v10 broke so much lol

**Comment by CDeenen** [comment]
Hey, I'm still working on making the module compatible with v10. It should be ready soon.

**Comment by iamthetot** [comment]
> Hey, I'm still working on making the module compatible with v10. It should be ready soon.

Thank you for your work on this module. I'm holding off on V10 until a few key modules are compatible, and this is one of them. Your work is appreciated!

**Comment by CDeenen** [comment]
I've just published the v10-ready update
